- calib-qa/cuts/rga-sp18.txt
close https://github.com/JeffersonLab/clas12-timeline/issues/3
> update FTOF specs

- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_t0_even_sec_sl.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_t0_odd_sec_sl.groovy
Add new groovy scripts to determine T0s for time spectra for different event time stamps (even and odd).
Code has been tested by Timothy on RGA data. Included code fix on hipo file names found by Andrey
> DC T0 for different event time stamp

- detectors/src/main/java/org/jlab/clas/timeline/fitter/DCFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec_rescut.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec_sl_rescut.groovy
- Add new DC timeline using max of histogram for residuals for each superlayer/sector
- Ensure that smaller sigma is used from double gaussian fit
- Improved fit range for double gaussian fit and display of fit in timeline plots. It didnt show up regularly.
- Removed mean/sigma timelines summed over superlayer with fitresidual cut (comment in run.groovy and run_rgb.groovy scripts). This is not really necessary and makes DC timelines more confusing. 
- Fixes to axis labels and timeline labels
> Update of DC timelines

- detectors/src/main/java/org/jlab/clas/timeline/fitter/HTCCFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/htcc/htcc_vtimediff_sector.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/htcc/htcc_vtimediff_sector_ring.groovy
- adding vtimediff timelines averaged over sector, and sector_ring combinations
- fix vtimediff fitting
- fix "mean/sigma" bug
> Htcc update

- monitoring/src/main/java/org/jlab/clas12/monitoring/RICH.java
- transition to the new RICH banks Ring and Particle
- now using pions and electrons
- momentum threshold increased from 1.5 to 2.0 GeV/c
- TO BE DONE: add the second module
> RICH update

- qa-physics/docs/docDiagram.md
> doc(QA): additional updates to flowchart

- qa-physics/README.md
- qa-physics/monitorRead.groovy
- qa-physics/studyCharge.C
- rename `FCmode` to `rechargeMode`, to make it more clear what this setting is used for
- clarify documentation comments
> style(QA): rename `FCmode` to `rechargeMode` and clarify documentation

- .github/workflows/ci.yml
- bin/build-all.sh
- monitoring/src/main/java/org/jlab/clas12/monitoring/LTCC.java
> ci: build test

- qa-physics/README.md
- qa-physics/deployTimelines.sh
- qa-physics/env.sh
- qa-physics/indexPage.groovy
- qa-physics/releaseTimelines.sh
- `CLASQAWWW` -> `TIMELINEDIR`
> refactor: make QA env variable names consistent

- qa-physics/monitorPlot.groovy
- fixes a memory leak in the file loop
- detects and skips corrupt input files
> fix(qa-physics): memory leak and corruption detection in `monitorPlot.groovy`

- .github/workflows/ci.yml
- bin/hipo-check.sh
- bin/hipo-trim.sh
Test timeline production with small statistics `mon`-schema files.
> ci: initial support for testing

- bin/run-detectors-timelines.sh
> fix: remove empty detector timelines directories

- .github/workflows/ci.yml
Add a summary output showing the final output file tree.
> ci: summarize output file tree

- .github/workflows/ci.yml
Fixes incomplete https://github.com/JeffersonLab/clas12-timeline/pull/119
> fix(ci): stream summary output file tree line-by-line

- bin/deploy-timelines.sh
- bin/run-detectors-timelines.sh
- bin/run-monitoring.sh
- bin/run-physics-timelines.sh
- bin/set-input-dir.sh
> fix: do not force output files to be in source code directory

- .github/workflows/ci.yml
- bin/dump-timelines.groovy
Until resolution of #85, let's at least dump the list of timelines. This could be extended to print images of the plots.
> ci: dump list of timelines to summary

- qa-physics/monitorRead.groovy
cherry picked from #108, since we want this in production now.
> fix: do not correct for wrong helicity

- bin/deploy-timelines.sh
- bin/run-detectors-timelines.sh
- bin/run-physics-timelines.sh
This allows users to say `-h` or `--help` midway through writing a command, to check the usage guide.
> feat: add usage guide options `-h` and `--help` to primary wrapper scripts

- bin/run-detectors-timelines.sh
I often find myself doing this manually, so it's time for a new option to automate this.
Use `run-detectors-timelines.sh --debug -t some_timeline` to more clearly see `stdout` and `stderr`, combined, for a specific timeline `some_timeline`. Execution will stop after the `run*.groovy` step.
> feat: add `--debug` mode for debugging specific detector timelines

- .github/workflows/ci.yml
Since it takes almost 10 minutes!
> ci: disable timeline dump summary step

- README.md
- Add example commands for each Step
- clarify Step 1's `clas12-workflow` usage
> doc: add examples

- README.md
- bin/run-physics-timelines.sh
- detectors/src/main/java/org/jlab/clas/timeline/util/Tools.groovy
- qa-physics/QA/modifyQaTree.groovy
- qa-physics/README.md
- qa-physics/datasetOrganize.sh
- qa-physics/docs/docDiagram.md
- qa-physics/exeQAtimelines.sh
- qa-physics/mergeFTandFD.groovy
- qa-physics/qaCut.groovy
- qa-physics/stageTimelines.sh
Pull in https://github.com/c-dilks/clasqa/pull/1 from @lucillalanza and update it to work in this new version of `clas12-timeline`.
Closes #110
> feat: add FT QA from Lucilla

- qa-physics/monitorRead.groovy
Preparing for pass1 readiness review using data from:
```
/volatile/clas12/rg-c/production/pass0/mon/v1.08_sqlite/mon/recon/
```
> feat(qa-physics): RG-C fall 22 settings

- bin/run-detectors-timelines.sh
- detectors/src/main/java/org/jlab/clas/timeline/fitter/CTOFFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/fitter/HTCCFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/util/HistoUtil.groovy
> fix: "WARNING in HistoUtil.getHistoIQR: attempt to calculate median of an empty list" warnings from RG-A Sp18

- bin/run-monitoring.sh
This speeds up `run-monitoring.sh` for QA timelines by orders of magnitude.
> fix: don't run `hipo-check` for trains

- qa-physics/README.md
We have been asked to violate one of these rules yet another time, so let's put them in the documentation.
> doc: QA procedure rules

- detectors/src/main/java/org/jlab/clas/timeline/fitter/ForwardFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_EleVz.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_NegVz.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_PosVz.groovy
The RG-D has a double target, so the fit for the forward electron Vz needs to use a double Gaussian + a first-order polynomial function.
Here is the fit function. 
The issue is whether it needs to be run-group or run-depend. 
The fitting range and initial values are specific for RG-D.
@c-dilks
> Change fit function for RG-D for the forward electron Vz.

- monitoring/src/main/java/org/jlab/clas12/monitoring/monitor2p2GeV.java
> fix: RG-D run range in `testTriggerSector`

- detectors/src/main/java/org/jlab/clas/timeline/fitter/ForwardFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_EleVz.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_NegVz.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/forward/forward_Tracking_PosVz.groovy
I have changed the range for the fit for the BiModal function to fit only the two peaks. 
I have also changed the initial values for the fits. 
I have added an if statement to apply the double Gaussian only on solid targets for RG-D.
> Change range and inital values for the fit function for forward Vz for RG-D. Apply the double gaussian fit only for solid target.

- qa-physics/docs/docDiagram.md
> doc: update flowchart for helicity-latched charge handling

- qa-physics/monitorPlot.groovy
Fix the calculation of a run's average kinematic value (DIS kinematics, pion kinematics).
Current behavior: make a distibution of each QA bin's average, then take the average of that distribution, _i.e._, an average of an average
Corrected behavior: take the average of the _sum_ of the bins' distributions
> fix(physics): kinematics timelines average calculation

- bin/hipo-check.sh
- bin/run-detectors-timelines.sh
RG-L may start causing some timeline HIPO files to be bad/empty. In particular, `ftof_ctof_vtdiff` is empty for current RG-L data.
This should not prevent Step 2 from running to completion, but we need to prevent the bad HIPO files from being deployed. The bad timemlines are now removed and the user is warned.
> hotfix: remove bad timeline HIPO files and allow Step 2 to finish

- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc.groovy
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- if before RG-L, don't even run the timeline engine
- if during RG-L, run the engine, but if data are empty, don't attempt to produce the final timeline and instead complain to `stderr` so the chef sees the issue
Fixes #307
> fix: don't attempt to analyze empty ALERT timelines

- doc/dev_notes.md
This PR adds the instruction for the issue #13.
Fixes #13
Closes #13
Resolves #13
Upon merged, Delete issue_13
> Add the dev's instruction for the issue #13

- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_EleVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_NegVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_PosVz.groovy
- src/main/java/org/jlab/clas/timeline/fitter/ForwardFitter.groovy
Add a separate vertex fit function, adapted from Mohammad Hattawy's RG-F vertex fit function.
> fix: RG-L vertex fits

- .github/workflows/ci.yml
- bin/qtl
> build: use more reliable method to get version number

- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number1.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number2.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number3.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number4.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number5.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number6.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number7.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_ahdc_adc_layer_number8.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_minus_start_time_sector_0_4.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_minus_start_time_sector_10_14.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_minus_start_time_sector_5_9.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_sector_0_4.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_sector_10_14.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc_sector_5_9.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tot_sector_0_4.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tot_sector_10_14.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tot_sector_5_9.groovy
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_start_time.groovy
- src/main/java/org/jlab/clas/timeline/histograms/ALERT.java
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- Three changes; Increase TOT range, Add a 2D histogram of TOT vs TDC - start time, Add an AHDC ADC in ALERT.java
> Another set of major changes for the ALERT.

- qadb/src/modifyQaTree.groovy
This was needed for RG-C QADB production.
> feat(qadb): add another `modify.sh` custom action

- bin/qtl-histogram
- src/main/java/org/jlab/clas/timeline/run_histograms.java
> fix: remove 100M event limit

- doc/qa.md
small update to the QADB production checklist
> doc(QADB): command for checking beam energy from step-1 logs

- src/main/java/org/jlab/clas/timeline/util/RunDependentCut.groovy
RG-L run is complete.
Close #325
> fix: upper bound for RG-L run range
