- detectors/src/main/java/org/jlab/clas/timeline/fitter/DCFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec_rescut.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec_sl.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/dc/dc_residuals_sec_sl_rescut.groovy
Update for DC plots. Added new set of timelines for histograms with cuts similar to DC4gui (Repository: https://github.com/JeffersonLab/clas12calibration-dc, function passCalibCuts in https://github.com/JeffersonLab/clas12calibration-dc/blob/master/src/main/java/org/clas/detector/clas12calibration/dc/calt2d/T2DCalib.java). Also add double gaussian fitter But only take smaller sigma for timelines (no weighting with amplitude as it is done in DC4gui).
This update has been tested by Justin on RGM and RGB data (thank you). It requires also updated monitoring code.
> Update on DC plots for timelines

- monitoring/src/main/java/org/jlab/clas12/monitoring/tof_monitor.java
The ddoca term summations was wrongly added in some previous version before monitoring code was merged with the timeline code.
> DC monitoring: removed ddoca term from filling residuals

- calib-qa/cuts/cuts.txt
- calib-qa/util/applyBounds.groovy
As requested by @dcarman:
```
1) htcc nphe sec QA: 11-13                => already exists and these are the current cuts
2) htcc vtimediff mean QA: -1 ns to 1 ns  => new cuts
3) htcc vtimediff sigma QA: 1 ns          => new cuts (and underlying timeline needs to be fixed)
```
> feat: QA cuts for HTCC `vtimediff` timelines

- README.md
- detectors/README.md
Use relative links, so that they are functional on any branch.
Does not fix this `calib-qa` one, since #27 will: https://github.com/JeffersonLab/clas12-timeline/blob/bfe82833896c872eddb68904b508890ed0ebe6b1/README.md?plain=1#L66
> doc: replace hard github links with relative links

- bin/build-all.sh
- detectors/pom.xml
- monitoring/pom.xml
* coatjava 8.5.0 or later is necessary for a CCDB update to access certain tables, e.g., for RICH
* make the build system not require "realpath", and assume the standard /bin/bash location
> Move to newer coatjava version, make build more general

- qa-physics/qaCut.groovy
- qa-physics/qaPlot.groovy
Update FC charge timelines:
- gated (renamed)
- ungated (renamed and fixed, so it is calculated _independent_ of livetime)
- gated accumulated (renamed)
Update Livetime timelines, so now we have two versions:
- from total gated/ungated FC charge
- from average of `RUN::scaler::livetime` (new timeline)
> feat(QA): update livetime and FC charge timelines

- qa-physics/README.md
- qa-physics/monitorRead.groovy
- qa-physics/studyCharge.C
RGM breaks the correlation between `FCmode==1` and recharge option being on. Revert the name of this variable and clarify documentation.
> style(QA): rename `rechargeMode` back to `FCmode` and clarify documenation

- qa-physics/datasetListParser.sh
- qa-physics/datasetOrganize.sh
- qa-physics/exeSlurm.sh
- qa-physics/getListOfDSTs.sh
- fixes a bug where a `dataset` name is found more than once in `datasetList.txt`, causing parsing issues (even when the string appears in a comment)
- centralizes `datasetList.txt` parsing in a sourceable script
> fix: do not parse duplicate datasets in `datasetList.txt`

- bin/qa.sh
Allows one to override `TIMELINEDIR` without having to set an env var from the shell.
> feat: add options for running `qa-detectors` timelines

- monitoring/src/main/java/org/jlab/clas12/monitoring/RICH.java
Removed from the hipo output the DTime vs channel histograms to fix a memory error
> Update of the RICH: removed DTime vs channel histogram from the hipo out

- bin/qa.sh
- bin/slurm-mon12.sh
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
- qa-detectors/util/applyBounds.groovy
- qa-physics/QA/import.sh
- qa-physics/QA/modifyQaTree.groovy
- qa-physics/QA/parseQaTree.groovy
- qa-physics/Tools.groovy
- qa-physics/datasetListParser.sh
- qa-physics/datasetOrganize.sh
- qa-physics/deployTimelines.sh
- qa-physics/exeQAtimelines.sh
- qa-physics/exeSlurm.sh
- qa-physics/exeTimelines.sh
- qa-physics/getListOfDSTs.sh
- qa-physics/integrityCheck.sh
- qa-physics/jcacheRun.sh
- qa-physics/jprint.groovy
- qa-physics/mkTree.sh
- qa-physics/monitorRead.groovy
- qa-physics/qaCut.groovy
- qa-physics/releaseTimelines.sh
To allow for errors to be more easily seen in log files, redirect them to `stderr`.
> fix: error printouts should stream to `stderr`

- qa-physics/exeSlurm.sh
https://github.com/JeffersonLab/clas12-timeline/pull/72 introduced a bug where if one specifies a `/cache` directory, and the files are not (yet) on tape, the job list will not be populated.
This PR resolves the issue by generating jobs from `/cache`, not `/mss`.
@esteejus
> fix(qa-physics): generate Slurm jobs from specified directory, not tape stubs directory

- .github/workflows/ci.yml
Run the `deploy-timelines.sh` script, as a final step in CI pipelines. This job can be required to pass for any PR to the protected trunk branch.
After https://github.com/JeffersonLab/clas12-timeline/issues/85 resolution, this job could be extended to a Github Pages deployment.
> ci: add `bin/deploy-timelines.sh` job

- monitoring/pom.xml
This allows us to use features such as [type inference](https://openjdk.org/jeps/286).
> build: use Java 11 for `monitoring/`

- detectors/src/main/java/org/jlab/clas/timeline/fitter/DCFitter.groovy
- monitoring/src/main/java/org/jlab/clas12/monitoring/FT.java
- monitoring/src/main/java/org/jlab/clas12/monitoring/HTCC.java
- monitoring/src/main/java/org/jlab/clas12/monitoring/cndCheckPlots.java
> fix: protect fit parameter limits against `min==max`

- bin/run-detectors-timelines.sh
- bin/run-physics-timelines.sh
Fix #117 and adds this option to `run-physics-timelines.sh` for consistency
> fix: missing `-o` option in `run-{physics,detectors}-timelines.sh`

- qa-physics/monitorRead.groovy
The responsibility of QA is to identify problems, not fix them. This PR removes the silent FC attenuation fix used for RG-B data, since such fix is preferred in the data production itself.
> fix: remove FC attenuation correction for RG-B

- bin/run-monitoring.sh
Restrict detector timelines' version beam energy to only be used when running detector timelines; we don't want to run this lookup when running with `--focus-physics`.
> fix: only get `detector` timeline beam energy for `detector` timelines

- bin/run-detectors-timelines.sh
Backing up produced timelines can cause unnecessary and rapid disk space consumption during routine online timeline production (viz. RG-D); so let's just remove them.
Backups from `run-monitoring.sh` may remain and still be useful, since these backups are not created in SWIF running.
> fix: do not backup previous detector timelines

- README.md
- bin/run-monitoring.sh
We now have 2 requests to make `run-monitoring.sh` documentation simpler.
- Terse documentation with a suggested typical command will be printed by default; use `--help` for the full documentation
- Sets the default input-finding mode to `--findhipo`
> doc: add quick-start guide to `run-monitoring.sh`

- bin/run-detectors-timelines.sh
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
BAND is not included in RG-D timelines, since it uses the default `run.groovy` set. This hotfix will use RG-B's `run_rgb.groovy` script for RG-D so that BAND is visible.
Makes https://github.com/JeffersonLab/clas12-timeline/issues/74 worse, but seeing BAND timelines is a higher priority.
> hotfix: use `run_rgb.groovy` for RG-D, to include BAND timelines

- .gitignore
- README.md
- bin/run-physics-timelines.sh
- qa-physics/QA/import.sh
- qa-physics/README.md
- qa-physics/buildChargeTree.groovy
- qa-physics/datasetOrganize.sh
- qa-physics/docs/docDiagram.md
- qa-physics/exeQAtimelines.sh
- qa-physics/getListOfDSTs.sh
- qa-physics/integrityCheck.sh
- qa-physics/mkTree.sh
- qa-physics/monitorPlot.groovy
- qa-physics/qaCut.groovy
- qa-physics/qaPlot.groovy
- qa-physics/stageTimelines.sh
The transient files `qa-physics/out{dat,mon}.$dataset` files are used by practically all scripts in `qa-physics`, another issue similar to #115. This PR continues the idea of #122, allowing for flexibility of the placement of these transient files.
> fix: do not force transient `qa-physics` files to be in `qa-physics/` source directory

- .github/workflows/ci.yml
- bin/run-detectors-timelines.sh
- detectors/src/main/java/org/jlab/clas/timeline/timeline/epics/epics_xy.groovy
The number '8' comes from the default number of threads used for this script. This fix should bring back the missing ECAL SF timeline for @forcar.
> fix: `run-detectors-timelines.sh` skips every 8th timeline

- detectors/src/main/java/org/jlab/clas/timeline/fitter/FTOFFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/ftof/ftof_time_noTriggers_p1a.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/ftof/ftof_time_noTriggers_p1b.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/ftof/ftof_time_p1a.groovy
- detectors/src/main/java/org/jlab/clas/timeline/timeline/ftof/ftof_time_p1b.groovy
FTOF p1b vertex time timeline for RG-D after 18607 have bad fits. This PR makes p1a and p1b use the same fit method, with compromising initial fit parameters.
This should be tested on the full RG-D timeline.
> fix: stabilize FTOF p1b vertex time fits

- monitoring/src/main/java/org/jlab/clas12/monitoring/ana_2p2.java
- monitoring/src/main/java/org/jlab/clas12/monitoring/monitor2p2GeV.java
* indent/format and remove unused imports, variables, non-helpful comments
* RG-D address trigger bits
> More flexible trigger bit usage

- detectors/src/main/java/org/jlab/clas/timeline/fitter/ECFitter.groovy
RG-C run 16907 fit hangs and throws no errors. This PR attempts to fix the issue by using a variable RMS for the initial fit parameter, instead of a fixed and very small guess.
> fix: stalled fit in `ec_ecou_time`

- qa-detectors/cuts/cuts.txt
- qa-detectors/util/applyBounds.groovy
The parser's tokenization uses SPACEs as its delimiter, so TABs will be a part of the tokens. This PR throws an error if a TAB is detected in a token, and informs the user to replace TABs with SPACEs.
> fix(qa-detectors): catch TABs in `cuts.txt` parser

- bin/dump-timelines.groovy
> fix: print run number as integer in `dump-timelines.groovy`

- .github/workflows/ci.yml
See https://github.com/actions/upload-artifact/issues/478
Fortunately `download-artifact` now supports globbing.
> fix(ci): v4 artifact actions require unique artifact names

- bin/run-detectors-timelines.sh
- detectors/src/main/java/org/jlab/clas/timeline/helicity/helicity.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run.groovy
- detectors/src/main/java/org/jlab/clas/timeline/run_rgb.groovy
- monitoring/src/main/java/org/jlab/clas12/monitoring/ana_2p2.java
- monitoring/src/main/java/org/jlab/clas12/monitoring/helicity.java
> add helicity timeline

- monitoring/src/main/java/org/jlab/clas12/monitoring/tof_monitor.java
Error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
at org.jlab.clas12.monitoring.tof_monitor.fillCTOFFTOFTiming(tof_monitor.java:724)
at org.jlab.clas12.monitoring.tof_monitor.processEvent(tof_monitor.java:909)
at org.jlab.clas12.monitoring.ana_2p2.main(ana_2p2.java:84)
```
Resolved by using a variable length array.
> fix: OOB error in fixed-length array from `tof_monitor.java`

- qa-physics/README.md
- qa-physics/qaCut.groovy
- qa-physics/qaPlot.groovy
- gated and ungated FC charge and livetime are not sector dependent -> draw only one plot, rather than duplicating them 6 times
- remove the N/F histograms since they are not useful
- organize the plots better
This cuts the plots by more than half, and this will be useful with fine time bins, which take a while to load on slower computers.
> perf: reduce the number of physics-QA plots

- .github/workflows/ci.yml
blocker bug from 4.0.19 is resolved: https://issues.apache.org/jira/browse/GROOVY-11328
> ci: revert to testing with latest groovy v4

- qa-physics/monitorPlot.groovy
- qa-physics/monitorRead.groovy
The bin-by-bin FC charge calculated via the difference of the values at the bin boundaries is very slightly different from the charge calculated by the bin's max charge minus the min charge. This difference is because the FC charge vs. timestamp is slightly non-monotonic for data prior to RG-C. While the effect is expected to be very small, we add a timeline to make sure that it is.
> feat(physics): timeline for FC charge non-monotonicity

- detectors/src/main/java/org/jlab/clas/timeline/fitter/HTCCFitter.groovy
Improvement over #199. This seems to improve the overall fit stability for RG-E.
> fix: use IQR for initial `sigma` for HTCC vtimediff fit stabilization

- detectors/src/main/java/org/jlab/clas/timeline/fitter/CTOFFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/fitter/HTCCFitter.groovy
- detectors/src/main/java/org/jlab/clas/timeline/util/HistoUtil.groovy
- initial fit parameter 'sigma' guess was set to max(RMS, 0.2), which was almost always 0.2; using IQR/2 instead of RMS (to get rid of outlier bin bias) helped fix the worse-case outlying fits
- reducing the initial fit range (which readjusts itself iteratively, if I understand correctly) helped correct the fits in the way Daniel expected, and the overall fit result 'sigma' is reduced
> fix: undershooting Gaussian fits of `ctof_time`

- qa-detectors/README.md
- qa-detectors/cuts/cuts.txt
- qa-detectors/util/applyBounds.groovy
- until now, all QA'd detector timelines require _both_ a minimum and a maximum cut; this PR establishes 4 cut types:
- range (both min and max)
- min only
- max only
- none (trivial case)
- `cuts*.txt` columns use the string `NB` to specify "no bound"
- all relevant timelines, _viz._ the `sigma` timelines, use `NB` where relevant
- **`htcc_nphe_sec_npheMean` cuts are changed such that there is no upper bound** (requested by @IzzyIllari)
> feat: `qa-detectors` min-only and max-only cuts

- qa-physics/monitorPlot.groovy
RG-C timelines have _offset_ asymmetries, so we now:
- fit BSA to the function: $A_{LU} = A_{LU}^{\mbox{offset}} + A_{LU}^{\mbox{amplitude}}\sin\phi_h$
- make timelines for both amplitude and offset
> feat(physics): timeline for beam-spin asymmetry constant offset

- qa-physics/monitorPlot.groovy
The beam charge asymmetry _uncertainty_ is wrong; since it's not clear how to calculate it, just remove it for now.
> fix: remove incorrect beam charge asymmetry uncertainty

- qa-physics/monitorRead.groovy
Before this fix, the helicity distribution was also being filled when we _don't_ have `REC::Event`, which can skew the fraction of events with a defined helicity, especially for prescaled trains.
> fix(physics-qa): only fill helicity distribution when we have `REC::Event`

- bin/run-monitoring.sh
This prevents them from being clobbered if we want to process the same run number but with different dataset names.
> fix: slurm script names should include `$dataset` for uniqueness

- detectors/src/main/java/org/jlab/clas/timeline/fitter/CTOFFitter.groovy
If the first peak fit is bad, it's possible that the 2nd peak finder will try to search for a peak in an _empty_ dataset, since the 1st peak's sigma may be wider than the full histogram range. In this bad case, just equate the 1st and 2nd peak positions so we get 2 bad fits that are equivalent.
> fix: handle bad `ctof_tdcadc` fits

- detectors/src/main/java/org/jlab/clas/timeline/timeline/cvt/cvt_efficiency.groovy
If CVT efficiency data have not yet been generated for all runs in a dataset's run range, add a point at `(0,0)` on the timeline so that the front-end does not hang. The plot title is also modified to inform the viewer.
> fix: handle missing CVT efficiency data

- detectors/src/main/java/org/jlab/clas/timeline/timeline/ftof/ftof_ctof_vtdiff.groovy
Issue caused by #233 and identified by #234.
With this PR, we are safe to update the xrootd validation files.
> fix: require non-empty `ftof_ctof_vtdiff` histograms before fit attempt

- detectors/src/main/java/org/jlab/clas/timeline/fitter/CTOFFitter.groovy
- monitoring/src/main/java/org/jlab/clas12/monitoring/central.java
- CTOF vertex time bins are now 25 ps instead of 40 ps, to match the calibration suite
- the fit range is left narrower than that of the calibration suite, since it currently produces better fits
- we'll need an understanding of the difference between the calibration suite's histogram production and the production done here; for example, cut differences
> fix: decrease CTOF time bins from 40 ps to 25 ps

- detectors/src/main/java/org/jlab/clas/timeline/fitter/RICHFitter.groovy
RG-D run 18355 was stalling, because of a bad fit. I found that setting the lower bound of `sigma` helps make this fit converge. I also added a timeout to the fit routine, which will abort the fit after 10 seconds.
However, it seems that RG-D's fits are quite bad for this timeline, but that's a problem for another PR.
> fix: `rich_dt_m` sigma bounds and timeout bad fits

- qa-physics/README.md
ground rules moved to QADB repo via https://github.com/JeffersonLab/clas12-qadb/pull/59
> doc: ground rules link

- qa-physics/cutdefs/rga_fa18_inbending_nSidis.json
- qa-physics/cutdefs/rga_fa18_outbending_nSidis.json
- qa-physics/cutdefs/rga_sp19.json
> fix: adjust `PossiblyNoBeam` thresholds for RG-A

- .github/dependabot.yml
- bin/run-monitoring.sh
- detectors/pom.xml
- qa-physics/monitorRead.groovy
- ~allows @dependabot to keep it up-to-date~ yes, but for now we need to keep it at 1.2 (see #267)
- fixes #265 by moving the dependency resolution from runtime to build-time
> fix(build): use `maven` for dependency `org.apache.commons`

- bin/environ.sh
Error log files should be empty unless there are problems.
> fix: stop spamming `stderr` with unhelpful messages

- qa-physics/monitorRead.groovy
Since the FC charge is wrong for RG-D, we don't want to produce the beam charge asymmetry timeline.
- do not fill the helicity-latched FC charge-weighted helicity distribution
- beam charge asymmetry timeline should therefore be empty
- corresponding HIPO file will be trashed
> fix: do not calculate beam charge asymmetry for RG-D

- monitoring/src/main/java/org/jlab/clas12/monitoring/HTCC.java
This warning was being thrown because collections were being initialized without the type specified.
> fix: Resolved `uses unchecked or unsafe operations` compilation warning.

- bin/deploy-timelines.sh
Adds the option `-n` to `deploy-timelines.sh`, to add a note for the clas12mon webpage. This is done by generating a `README` file with the user-specified note; many chefs have been doing this manually.
> feat: deploy `README` note

- qa-physics/buildChargeTree.groovy
fixes #281 
Moves `monitor_*.hipo` file handling to its own loop, which iterates over QA bins for each run.
HIPO files were not being closed, since `monFile` and `inMdir` never go out of scope; each new file and its histograms persists in memory. 
Basically, instead of 
```groovy
def obj // global scope
run_list.each {
obj = new ...
}
```
do this:
```groovy
run_list.each {
def obj = new ... // scoped for only this iteration
}
```
> fix: OutOfMemoryError from `buildChargeTree.groovy`

- qa-physics/stageTimelines.sh
This timeline is not so important for Pass readiness reviews, _etc._
> refactor: move FC charge non-monotonicity to `PHYS_QA_EXTRA` webpage

- detectors/src/main/java/org/jlab/clas/timeline/fitter/HTCCFitter.groovy
Very narrow gaussians seem to be causing the following crashes in RG-E timelines:
```
java.lang.RuntimeException: Something is wrong!
at org.freehep.math.minuit.VariableMetricBuilder.minimum(VariableMetricBuilder.java:50)
at org.freehep.math.minuit.VariableMetricBuilder.minimum(VariableMetricBuilder.java:21)
at org.freehep.math.minuit.ModularFunctionMinimizer.minimize(ModularFunctionMinimizer.java:29)
at org.freehep.math.minuit.ModularFunctionMinimizer.minimize(ModularFunctionMinimizer.java:21)
at org.freehep.math.minuit.MnApplication.minimize(MnApplication.java:58)
at org.freehep.math.minuit.MnApplication.minimize(MnApplication.java:43)
at org.freehep.math.minuit.MnApplication.minimize(MnApplication.java:39)
at org.jlab.groot.fitter.DataFitter.fit(DataFitter.java:84)
at …
```
> fix(htcc_vtimediff): increase `sigma` fit-param min

- bin/run-detectors-timelines.sh
- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc.groovy
- src/main/java/org/jlab/clas/timeline/fitter/ALERTFitter.groovy
- src/main/java/org/jlab/clas/timeline/histograms/ALERT.java
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- src/main/java/org/jlab/clas/timeline/run_histograms.java
This PR consists of three major commits and two minor fixes for the ALERT timeline.
These are all prelim in sense that it only produces the ATOF TDC peak location/ sigma/ integral (normalized to the trigger.)
It is timeliy to include in the main branch to get the feedbacks from the ALERT experts.
1. [Add the prelim ALERT monitoring](https://github.com/JeffersonLab/clas12-timeline/commit/291cd19398dc4e2cad7047e787bde219acec0147)
- Add the [ALERT.java](https://github.com/JeffersonLab/clas12-timeline/tree/alert-dev/src/main/java/org/jlab/clas/timeline/histograms/ALERT.java) to save the histograms in out_ALERT_`runnum`.hipo
- Edit the [run_histograms.java](https://github.com/JeffersonLab/clas12-timeline/tree/alert-dev/src/main/java/org/jlab/clas/timeline/run_histograms.java) to include the …
> Add the preliminary ALERT timeline to the main branch

- .github/workflows/ci.yml
- .mvn/maven.config
- doc/setup.md
- install.sh
- pom.xml
- use `--no-transfer-progress` to avoid filling CI logs with about 30,000 completely useless lines of download progress status
- use `maven-dependency-plugin` goal `copy-dependencies` instead of running the goal from the command line (via wrapper script), which seems to be much quieter too
- now we're back to just running `maven install` instead of a wrapper (`install.sh`)
> build: much quieter Maven output

- .github/workflows/ci.yml
When the cache hits (which is pretty much always), it's much faster to just use the runner, rather than wait for the container image pull. The job will be about 4 seconds, rather than 1-3 minutes.
> perf(ci): revert `download_test_data` to use runner rather than container

- src/main/java/org/jlab/clas/timeline/analysis/alert/alert_atof_tdc.groovy
- src/main/java/org/jlab/clas/timeline/analysis/ftof/ftof_ctof_vtdiff.groovy
Instead, warn about it. These timelines are empty for RG-L data.
_cf_. #308
> fix: do not try to write empty `ftof_ctof_vtdiff` timeline

- bin/qtl-analysis
`--debug` is used to help debug a single timeline, so just require `-t`.
> fix: `qtl analysis` option `--debug` should require `-t`

- bin/qtl-analysis
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
The RG-L chef reported that the fitting for the ATOF::tdc takes too long, and this has been an obstacle in producing the timeline.
We checked that the monitoring histograms were fine.
So I have disabled the ALERT timeline as a hot fix.
@c-dilks, Please release this version to the ifarm at your convenience.
Thank you!
> Disable the ALERT: revert the changes in 0ad16c1 and 0118be5

- doc/chef_guide.md
- doc/dev_notes.md
- doc/procedure.md
- clarify step 1 is integrated in cooking workflow
- remove links to `clas12-workflow`, in favor of just linking once to the chef wiki (avoid link rot)
> doc: clarify step 1 chef and dev usage

- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_EleVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_NegVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_PosVz.groovy
- src/main/java/org/jlab/clas/timeline/histograms/GeneralMon.java
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- src/main/java/org/jlab/clas/timeline/util/RunDependentCut.groovy
We have a lot of run-number dependence throughout, which is currently tracked by #74. Instead of continuing to add to the list, in desperate hope of a general solution, let's mitigate by keeping track of _where_ the run-number dependent conditionals are used. We can do this by using custom run-number cut functions in a new class `RunDependentCut`.
We can't enforce its usage, but we can try to be consistent.
Many of these functions are very simple, but it makes it much easier to find all the run-dependent cuts, should we return to the idea of some configuration file implementation later.
I think this is good enough for now, since it's more flexible than a configuration file, so I'd say this closes #74.
> refactor: run-number dependent conditionals should use `RunDependentCut`

- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- excludes irrelevant timelines for RG-L
- checks each run whether it should be processed for the timeline
- timelines are only actually produced if at least one run is processed
- sorry, I couldn't resist doing a bit of cleanup too -> hide whitespace when viewing PR diff
A better approach would be to exclude these from Step 1 too, but many of the histograms are produced by `GeneralMon`, so that's not easy to do at the moment; so for now we waste some CPU time filling unused histograms.
> fix: exclude `BMTBST`, `CENTRAL`, and `CVT` from RG-L

- bin/qtl-analysis
Without this, it just silently exits `1` (since `grep` exits `1` when no match is found)
> fix: print error when `qtl analysis -m` matches no timeline

- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_EleVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_NegVz.groovy
- src/main/java/org/jlab/clas/timeline/analysis/forward/forward_Tracking_PosVz.groovy
- src/main/java/org/jlab/clas/timeline/histograms/GeneralMon.java
- src/main/java/org/jlab/clas/timeline/run_analysis.groovy
- src/main/java/org/jlab/clas/timeline/util/RunDependentCut.groovy
These are the only other ones we need for now. Following the YAGNI rule and not adding any others until needed.
> refactor: add RG-D and RG-L to `RunDependentCut.findDataset`

- doc/dev_notes.md
- move to the top for better visibility
- use auto-linking instead of full URLs
- no changes to the text, other than minor formatting
> doc: move 'how to add new timelines' notes to the top

- bin/qtl-histogram
- src/main/java/org/jlab/clas/timeline/get_beam_energy.groovy
Get the beam energy for all the runs with one DB connection instance, rather than one per run. This is _significantly_ faster.
> perf: decrease step 1 startup time

- bin/qtl-analysis
- bin/qtl-physics
If it doesn't exist, `realpath` will fail. Could also be fixed by `realpath -m`, but we are really only using `realpath` to sanitize custom output directory arguments (the default output directory already uses `$(pwd -P)`
> fix(qtl-analysis): make output directory before `realpath`

- bin/qtl-analysis
- pom.xml
This allows the target publishing directory to be _clobbered_, as opposed to `--overwrite` (which removes and recreates).
@mathieuouillon reports that `--overwrite` has been causing the RG-L auto-pass0 timeline link to temporarily disappear from the clas12mon webpage; `--clobber` hopefully prevents that from happening.
Note that `--overwrite` will be needed for the rare case when we _remove_ a timeline, so that they get removed from the publishing directory (or just remove the HIPO files manually).
> feat: add `--clobber` option to `qtl analysis`
